# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/ECE385_final_project/ECE385_final_project.srcs/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_0/mb_block_axi_gpio_1_0.xci
# IP: The module: 'mb_block_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/ECE385_final_project/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_0/mb_block_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/ECE385_final_project/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_0/mb_block_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/ECE385_final_project/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_0/mb_block_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FPGA/ECE385_final_project/ECE385_final_project.srcs/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_0/mb_block_axi_gpio_1_0.xci
# IP: The module: 'mb_block_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/ECE385_final_project/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_0/mb_block_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/ECE385_final_project/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_0/mb_block_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/ECE385_final_project/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_0/mb_block_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
