# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ECE385_final_project_Final/ECE385_final_project.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/mb_block_hdmi_graph_controller_0_0.xci
# IP: The module: 'mb_block_hdmi_graph_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/hdmi_tx_0_1/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_sad_rom/Wojak_sad_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Wojak_sad_rom || ORIG_REF_NAME==Wojak_sad_rom} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_happy_rom/Wojak_happy_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Wojak_happy_rom || ORIG_REF_NAME==Wojak_happy_rom} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_normal_rom/Wojak_normal_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Wojak_normal_rom || ORIG_REF_NAME==Wojak_normal_rom} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/clk_wiz_0_1/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_sad_rom/Wojak_sad_rom_ooc.xdc

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_happy_rom/Wojak_happy_rom_ooc.xdc

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_normal_rom/Wojak_normal_rom_ooc.xdc

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/clk_wiz_0_1/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc

# IP: D:/ECE385_final_project_Final/ECE385_final_project.srcs/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/mb_block_hdmi_graph_controller_0_0.xci
# IP: The module: 'mb_block_hdmi_graph_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/hdmi_tx_0_1/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_sad_rom/Wojak_sad_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Wojak_sad_rom || ORIG_REF_NAME==Wojak_sad_rom} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_happy_rom/Wojak_happy_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Wojak_happy_rom || ORIG_REF_NAME==Wojak_happy_rom} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_normal_rom/Wojak_normal_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Wojak_normal_rom || ORIG_REF_NAME==Wojak_normal_rom} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/clk_wiz_0_1/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_sad_rom/Wojak_sad_rom_ooc.xdc

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_happy_rom/Wojak_happy_rom_ooc.xdc

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/Wojak_normal_rom/Wojak_normal_rom_ooc.xdc

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/clk_wiz_0_1/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/ECE385_final_project_Final/ECE385_final_project.gen/sources_1/bd/mb_block/ip/mb_block_hdmi_graph_controller_0_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc
