# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ECE_385/FINAL_PROJECT/ip_repo/hdmi_graph_controller_1_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE_385/FINAL_PROJECT/ip_repo/hdmi_graph_controller_1_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/ECE_385/FINAL_PROJECT/ip_repo/hdmi_graph_controller_1_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE_385/FINAL_PROJECT/ip_repo/hdmi_graph_controller_1_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
